# Generated by Django 3.1 on 2020-08-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200814_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.BooleanField(choices=[(0, 'Female'), (1, 'Male')], default=1, verbose_name='sex'),
        ),
    ]
