# Generated by Django 3.1 on 2020-08-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200814_0152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
