# Generated by Django 3.1 on 2020-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200814_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.BooleanField(choices=[(0, 'Female'), (1, 'Male')], default=0, verbose_name='sex'),
        ),
    ]
