# Generated by Django 3.1 on 2020-08-13 09:45

from django.db import migrations, models
import django.db.models.deletion
import drinks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anoymous', max_length=32, unique=True)),
                ('desc', models.TextField(max_length=512, null=True)),
                ('brand_img', models.ImageField(upload_to=drinks.models.get_image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('price', models.PositiveIntegerField(default=None, null=True)),
                ('desc', models.TextField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(null=True, upload_to=drinks.models.get_image_path)),
                ('food_images', models.ImageField(upload_to=drinks.models.get_foodimage_path, verbose_name='Image')),
                ('likes', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='drinks.brand')),
            ],
        ),
    ]
