# Generated by Django 3.1 on 2020-08-14 00:37

from django.db import migrations, models
import drinks.models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='food_images',
            field=models.ImageField(upload_to=drinks.models.get_foodimage_path),
        ),
    ]
