# Generated by Django 3.1 on 2020-08-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_auto_20200814_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='brand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='drinks', to='drinks.brand'),
        ),
    ]
