# Generated by Django 3.1 on 2020-08-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_auto_20200814_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_img',
            new_name='image',
        ),
    ]
